site_name: SPoNet
repo_url: https://github.com/lueckem/SPoNet

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [sponet]
          options:
            docstring_style: numpy
            merge_init_into_class: true
            docstring_section_style: list

nav:
  - Home: index.md
  - Collective Variables: collective_variables.md
