site_name: SPoNet
repo_url: https://github.com/lueckem/SPoNet

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [sponet]
          options:
            docstring_style: numpy
            merge_init_into_class: true
            docstring_section_style: list

nav:
  - Home: index.md
  - Collective Variables: collective_variables.md
  - Network Generators: network_generators.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
