site_name: SPoNet
repo_url: https://github.com/lueckem/SPoNet

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [sponet]
          options:
            docstring_style: numpy
            merge_init_into_class: true
            docstring_section_style: list
            members_order: source

nav:
  - Home: index.md
  - Reference:
    - CNVM: cnvm.md
    - Network Generators: network_generators.md
    - Collective Variables: collective_variables.md
    - Sampling States: states.md
    - Multiprocessing: multiprocessing.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
